const allWord50 = [
  { be: "бути" },
  { to: "до" },
  { of: "з, про" },
  { for: "для" },
  { it: "це" },
  { with: "з, із" },
  { as: "як" },
  { at: "на, у" },
  { near: "поруч" },
  { behind: "позаду" },
  { from: "з, від" },
  { or: "або" },
  { will: "буде" },
  { there: "там" },
  { out: "зовні, поза" },
  { who: "хто" },
  { which: "який" },
];

const allWord = [
  { difference: "різниця" },
  { confident: "впевнений" },
  { available: "доступний" },
  { changing: "змінюється" },
  { successful: "успішний" },
  { keep: "зберігати" },
  { believe: "вірити" },
  { matter: "має значення" },
  { already: "вже" },
  { through: "крізь" },
  { allows: "дозволяє" },
  { sets: "встановлює" },
  { fits: "підходить" },
  { explains: "пояснює" },
  { demands: "вимагати" },
  { relationships: "стосунки" },
  { assumes: "припускає" },
  { tells: "розповідає" },
  { spend: "витрачати" },
  { appear: "з'являтись" },
  { approximately: "приблизно" },
  { almost: "майже" },
  { responsible: "відповідальний" },
  { frequent: "часто" },
];

const allWordPhrases = [
  { "let's go": "ходімо" },
  { "let's do it": "зробимо це" },
  { "come here": "підійди сюди" },
  { "follow me": "йди за мною" },
  { "keep going": "продовжуй" },
  { "wait here": "почикай тут" },
  { "stay still": "залишся" },
  { "try it": "спробуй це" },
  { "give it to me": "дайте це мені" },
  { "be quiet": "тихо" },
  { "ask hime": "запитай його" },
  { "let go it": "відпусти це" },
  { "leave it here": "залиши це тут" },
  { "put it here": "постав це тут" },
  { "don't forget": "не забудь" },
  { "slow down": "повільніше" },
  { "can't complain": "не скаржусь" },
  { "see if I care": "мене це не хвилює" },
  { "I do not care": "мені всеодно" },
  { "I did it": "я зробив це" },
  { "It's up to you": "тобі вирішувати" },
  { "I'd like": "меніб хотілось" },
];

const allWordQuestion = [
  { "are you kidding?": "жартуєш?" },
  { "is he comming?": "він йде?" },
  { "are you getting anything?": "ти береш щось?" },
  { "you bring something?": "ти приносиш щось?" },
  { "is it getting better?": "це стає кращим?" },
  { "what are you wearing?": "у що ти одягнений?" },
  { "could I have?": "чи можна мені?" },
  { "What do you do for a living?": "Чим ви займаєтесь?" },
];

const vehicle = [
  { Brake: "гальма" },
  { Tire: "шина" },
  { Alternator: "генератор" },
  { Suspension: "підвіска" },
  { ExhaustSystem: "вихлопна система" },
  { Headlight: "фара" },
  { Taillight: "заднє світло" },
  { Windshield: "лобове скло" },
  { Wiper: "двірник" },
  { FuelTank: "паливний бак" },
  { SparkPlug: "свічка запалювання" },
  { IgnitionCoil: "котушка запалювання" },
  { FuelPump: "паливний насос" },
  { SteeringWheel: "кермо" },
];
const house = [
  { Roof: "дах" },
  { Wall: "стіна" },
  { Floor: "підлога" },
  { Ceiling: "стеля" },
  { Foundation: "фундамент" },
  { Chimney: "димар" },
  { Stairs: "сходи" },
  { Balcony: "балкон" },
  { Terrace: "тераса" },
  { Garage: "гараж" },
  { Garden: "сад" },
  { Fence: "пагорб" },
  { Gate: "ворота" },
  { Pathway: "доріжка" },
  { Porch: "веранда" },
  { Attic: "горище" },
  { Basement: "підвал" },
  { LivingRoom: "вітальня" },
  { Bedroom: "спальня" },
  { Bathroom: "ванна кімната" },
  { Kitchen: "кухня" },
  { DiningRoom: "їдальня" },
  { Study: "кабінет" },
  { Fireplace: "камін" },
  { Roofing: "покрівля" },
  { Insulation: "ізоляція" },
  { Plumbing: "сантехніка" },
  { Heating: "опалення" },
  { Cooling: "охолодження" },
  { Ventilation: "вентиляція" },
  { Skylight: "дахове вікно" },
  { Siding: "обшивка" },
  { Balustrade: "балюстрада" },
  { Shutter: "жалюзі" },
  { Awning: "навіс" },
  { Gutter: "сток" },
  { Lawn: "газон" },
  { Patio: "патіо" },
  { Driveway: "під'їзд" },
  { Shed: "хлів" },
  { Workshop: "мастерня" },
  { LaundryRoom: "пральня" },
  { Boiler: "котел" },
  { SolarPanel: "сонячна панель" },
  { AlarmSystem: "сигналізація" },
  { Intercom: "домофон" },
  { SecurityCamera: "відеокамера" },
];
const kitchen = [
  { Stove: "плита" },
  { Oven: "духовка" },
  { Refrigerator: "холодильник" },
  { Sink: "раковина" },
  { Dishwasher: "посудомийна машина" },
  { Microwave: "мікрохвильова піч" },
  { Blender: "блендер" },
  { Toaster: "тостер" },
  { Kettle: "чайник" },
  { CoffeeMaker: "кавоварка" },
  { Mixer: "міксер" },
  { CuttingBoard: "дошка для різання" },
  { Knife: "ніж" },
  { Fork: "виделка" },
  { Spoon: "ложка" },
  { Spatula: "лопатка" },
  { Ladle: "ковш" },
  { Pot: "кастрюля" },
  { Pan: "сковорода" },
  { BakingSheet: "пекарський лист" },
  { MixingBowl: "миска для змішування" },
  { MeasuringCup: "мірна чашка" },
  { CuttingKnife: "кухонний ніж" },
  { Colander: "дуршлаг" },
  { Grater: "терка" },
  { Peeler: "шкребок" },
  { CanOpener: "відкривачка для банок" },
  { UtensilHolder: "підставка для приладдя" },
  { MixingSpoon: "місцева ложка" },
  { Whisk: "венчик" },
  { Sifter: "сито" },
  { CuttingBoard: "дошка для різання" },
  { RollingPin: "каток для тіста" },
  { OvenMitts: "рукавиці для духовки" },
  { Apron: "фартух" },
  { PotHolder: "підставка для каструлі" },
  { KitchenScale: "кухонний ваги" },
  { FoodProcessor: "процесор харчів" },
  { BakingDish: "форма для запікання" },
  { Canister: "каністра" },
  { SpiceRack: "стійка для спецій" },
  { DishRack: "стійка для посуду" },
  { GarbageCan: "смітник" },
  { Timer: "таймер" },
  { Cookbook: "кулінарна книга" },
  { DiningTable: "стіл для обіду" },
  { Chair: "стілець" },
  { Plate: "тарілка" },
  { Bowl: "чаша" },
  { Cup: "чашка" },
  { Glass: "склянка" },
  { Napkin: "серветка" },
];

export { allWord50, allWord, allWordPhrases, allWordQuestion, vehicle, house, kitchen };
