const allWord50 = [
  { be: "бути" },
  { to: "до" },
  { of: "з, про" },
  { for: "для" },
  { it: "це" },
  { with: "з, із" },
  { as: "як" },
  { at: "на, у" },
  { by: "біля, за" },
  { from: "з, від" },
  { or: "або" },
  { will: "буде" },
  { there: "там" },
  { out: "зовні, поза" },
  { who: "хто" },
  { which: "який" },
];

const allWord = [
  { difference: "різниця" },
  { confident: "впевнений" },
  { available: "доступний" },
  { changing: "змінюється" },
  { successful: "успішний" },
  { keep: "зберігати" },
  { believe: "вірити" },
  { matter: "має значення" },
  { already: "вже" },
  { through: "крізь" },
  { allows: "дозволяє" },
  { sets: "встановлює" },
  { fits: "підходить" },
  { explains: "пояснює" },
  { demands: "вимагати" },
  { relationships: "стосунки" },
  { assumes: "припускає" },
  { tells: "розповідає" },
  { will: "бути" },
  { spend: "витрачати" },
  { appear: "з'являтись" },
  { approximately: "приблизно" },
  { almost: "майже" },
  { responsible: "відповідальний" },
  { frequent: "часто" },
];

const allWordPhrases = [
  { "let's go": "ходімо" },
  { "let's do it": "зробимо це" },
  { "зробимо це": "підійди сюди" },
  { "follow me": "йди за мною" },
  { "keep going": "продовжуй" },
  { "wait here": "почикай тут" },
  { "stay still": "залишся" },
  { "try it": "спробуй це" },
  { "give it to me": "дайте це мені" },
  { "be quiet": "тихо" },
  { "ask hime": "запитай його" },
  { "let go it": "відпусти це" },
  { "leave it here": "залиши це тут" },
  { "put it here": "постав це тут" },
  { "don't forget": "не забудь" },
  { "slow down": "повільніше" },
  { "can't complain": "не скаржусь" },
  { "see if I care": "мене це не хвилює" },
  { "I do not care": "мені всеодно" },
  { "I did it": "я зробив це" },
  { "It's up to you": "тобі вирішувати" },
];

const allWordQuestion = [
  { "are you kidding?": "жартуєш?" },
  { "is he comming?": "він йде?" },
  { "are you getting anything?": "ти береш щось?" },
  { "you bring something?": "ти приносиш щось?" },
  { "is it getting better?": "це стає кращим?" },
  { "what are you wearing?": "у що ти одягнений?" },
];

export { allWord50, allWord, allWordPhrases, allWordQuestion };
