const allWord50 = [
  { be: "бути" },
  { do : "робити" },
  { to: "до" },
  { of: "з, про" },
  { for: "для" },
  { it: "це" },
  { with: "з, із" },
  { as: "як" },
  { at: "на, у" },
  { near: "поруч" },
  { behind: "позаду" },
  { from: "з, від" },
  { or: "або" },
  { will: "буде" },
  { there: "там" },
  { out: "зовні, поза" },
  { who: "хто" },
  { which: "який" },
];

const allWord = [
  { difference: "різниця" },
  { confident: "впевнений" },
  { available: "доступний" },
  { changing: "змінюється" },
  { successful: "успішний" },
  { keep: "зберігати" },
  { believe: "вірити" },
  { matter: "має значення" },
  { already: "вже" },
  { through: "крізь" },
  { allows: "дозволяє" },
  { sets: "встановлює" },
  { fits: "підходить" },
  { explains: "пояснює" },
  { demands: "вимагати" },
  { relationships: "стосунки" },
  { assumes: "припускає" },
  { tells: "розповідає" },
  { spend: "витрачати" },
  { appear: "з'являтись" },
  { approximately: "приблизно" },
  { almost: "майже" },
  { responsible: "відповідальний" },
  { frequent: "часто" },
  { everyone: "усі" },
  { trip: "подорож" },
  { among: "серед" },
  { neighborhood: "околиці" },
  { average: "середній" },
  { majority: "більшість" },
  { half: "половина" },
  { example: "приклад" },
  { explanation: "пояснення" },
  { preparation: "підготовка" },
  { difficulties: "труднощі, складність" },
  { meaning: "зміст, сенс" },
  { agree: "погоджуватись" },
  { feels: "почуватися" },
  { wishes: "бажання" },
  { tries: "коштувати" },
  { either: "також, теж" },
  { sad: "сумно" },
];

const reWord = [
  { few: "декілька" },
  { "to break off": "відокремити, відламати" },
  { "to approach": "наближатися" },
  { "to match": "відповідати підходити" },
  { "to consome": "споживати, поглинати" },
  { "to find out": "зясовувати" },
  { "to earn": "заробляти" },
  { cupboard: "кухонна шафа" },
  { "to survey": "опитувати, оглядати" },
  { "to hold out": "триматися до кінця" },
  { "to aford": "дозво. фінансово" },
  { "to go over": "повторювати" },
  { "to lose": "втрачати, програвати" },
  { could: "міг, може бути" },
  { "to extract": "витягувати, добувати" },
  { forego: "відмовлятися" },
  { change: "здача" },
  { contest: "конкурс, змагання" },
  { "to crop": "обрізати, підстригти" },
  { loose: "вільний" },
  { influence: "впливати" },
  { wide: "широкий" },
  { "to mind": "заперечувати, слухатися" },
  { "to persuade": "переконувати" },
  { representative: "представник" },
  { source: "джерело, початковий" },
  { "to supplement": "доповнювати" },
  { "to owe": "заборгувати" },
  { "to blow out": "підірвати, гасити" },
  { interweave: "переплітати" },
];

const allWordPhrases = [
  { "let's go": "ходімо" },
  { "let's do it": "зробимо це" },
  { "come here": "підійди сюди" },
  { "follow me": "йди за мною" },
  { "keep going": "продовжуй" },
  { "wait here": "почикай тут" },
  { "stay still": "залишся" },
  { "try it": "спробуй це" },
  { "give it to me": "дайте це мені" },
  { "be quiet": "тихо" },
  { "ask hime": "запитай його" },
  { "let go it": "відпусти це" },
  { "leave it here": "залиши це тут" },
  { "put it here": "постав це тут" },
  { "don't forget": "не забудь" },
  { "slow down": "повільніше" },
  { "can't complain": "не скаржусь" },
  { "see if I care": "мене це не хвилює" },
  { "I do not care": "мені всеодно" },
  { "I did it": "я зробив це" },
  { "It's up to you": "тобі вирішувати" },
  { "I'd like": "меніб хотілось" },
];

const allWordQuestion = [
  { "are you kidding?": "жартуєш?" },
  { "is he comming?": "він йде?" },
  { "are you getting anything?": "ти береш щось?" },
  { "you bring something?": "ти приносиш щось?" },
  { "is it getting better?": "це стає кращим?" },
  { "what are you wearing?": "у що ти одягнений?" },
  { "could I have?": "чи можна мені?" },
  { "what do you do for a living?": "Чим ви займаєтесь?" },
];

const vehicle = [
  { brake: "гальма" },
  { tire: "шина" },
  { alternator: "генератор" },
  { suspension: "підвіска" },
  { exhaustSystem: "вихлопна система" },
  { headlight: "фара" },
  { taillight: "заднє світло" },
  { windshield: "лобове скло" },
  { wiper: "двірник" },
  { fuelTank: "паливний бак" },
  { sparkPlug: "свічка запалювання" },
  { ignitionCoil: "котушка запалювання" },
  { fuelPump: "паливний насос" },
  { trunk: "багажник" },
];
const house = [
  { roof: "дах" },
  { ceiling: "стеля" },
  { chimney: "димар" },
  { stairs: "сходи" },
  { fence: "пагорб" },
  { gate: "ворота" },
  { pathway: "доріжка" },
  { porch: "веранда" },
  { attic: "горище" },
  { basement: "підвал" },
  { livingRoom: "вітальня" },
  { bedroom: "спальня" },
  { bathroom: "ванна кімната" },
  { diningRoom: "їдальня" },
  { study: "кабінет" },
  { fireplace: "камін" },
  { roofing: "покрівля" },
  { plumbing: "сантехніка" },
  { heating: "опалення" },
  { skylight: "дахове вікно" },
  { siding: "обшивка" },
  { balustrade: "балюстрада" },
  { shutter: "жалюзі" },
  { awning: "навіс" },
  { gutter: "сток" },
  { lawn: "газон" },
  { driveway: "під'їзд" },
  { shed: "хлів" },
  { laundryRoom: "пральня" },
  { boiler: "котел" },
  { alarmSystem: "сигналізація" },
  { intercom: "домофон" },
];

const number = [
  { twelve: "12" },
  { thirteen: "13" },
  { fourteen: "14" },
  { fifteen: "15" },
  { sixteen: "16" },
  { seventeen: "17" },
  { eighteen: "18" },
  { nineteen: "19" },
  { twenty: "20" },
  { thirty: "30" },
  { forty: "40" },
  { fifty: "50" },
  { sixty: "60" },
  { seventy: "70" },
  { eighty: "80" },
  { ninety: "90" },
];

const months = [
  { January: "січень" },
  { February: "лютий" },
  { March: "березень" },
  { April: "квітень" },
  { May: "травень" },
  { June: "червень" },
  { July: "липень" },
  { August: "серпень" },
  { September: "вересень" },
  { October: "жовтень" },
  { November: "листопад" },
  { December: "грудень" },
];

const englishPrime = [
  { your : "твій" },
  { sell : "продавати" },
  { meet : "зустріти" },
  { walk : "ходити" },
  { carry : "тримати" },
  { "put on, in" : "поставити" },
  { "pick up" : "підняти" },
  { "talk (to)" : "говорити" },
  { take : "брати" },
  { tell : "розмова" },
  { wear : "носити" },
];

const SentencePattern = [
  {"Do you/we/they/your meet" : "ви зустрічаєтеся"},
  {"Yes I meet" : "так я зустрічаюсь"},
  {"No I do not meet" : "ні я не зустрічаюсь"},
  {"You don't meet" : "ви не зустрічаєтесь"},
  {"Does he meetS" : "так він зустрічається"},
  {"No, he does not meetS" : "ні він не зустрічається"},
  {"She doesn't meet" : "вона не зустрічаєця"},
  {"Do you want/like to talk" : "чи ти хочеш поговорити"},
  {"Yes I want/like to talk" : "так я хочу поговорити"},
  {"No, I don't want to talk" : "ні я нехочу поговорити"},
  {"Does, he want to talk" : "ні я нехочу поговорити"},
  {"Yes, he wantS to talk" : "так він хоче поговорити"},
  {"No,he does't to talk" : "ні він не хоче поговорити"},
]

export {
  allWord50,
  allWord,
  allWordPhrases,
  allWordQuestion,
  reWord,
  house,
  number,
  months,
  englishPrime,
  SentencePattern,
};
